--- 
  - name: This is Package Module Task 
    hosts: all
    become: true 
    tasks:
      - name: Install web server 
        package:
          name: apache2
          state: latest
          update_cache: yes

      - name: start web server
        ansible.builtin.service:
          name: apache2
          state: started
...
