---
- name: Installation of my web-server
  hosts: all
  become: true
  tasks:
    - name: install web package
      package:
        name: httpd
        state: latest
      when: ansible_os_family == "RedHat"
  
    - name: install web package
      package:
        name: nginx
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: start httpd
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"

    - name: start nginx
      service:
        name: nginx
        state: started
      when: ansible_os_family == "Debian"
...